---
- name: setup nginx container on each web server host
  become_user: ubuntu
  community.docker.docker_container:
    name: nginx
    image: nginx
    ports:
        - "80:80"
    mounts:
      - type: bind
      - source: /var/www/html/srdela.xyz
      - target: /var/www/html/srdela.xyz
      - read_only: yes
    